name: more_container_practice
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  group_list_view: ^1.0.6
  flutter_spinkit: ^5.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bmetro.jpg
    - assets/king.jpg
    - assets/dailynews.png
    - assets/harare24.png
    - assets/hmetro.jpg
    - assets/kwayedza.png
    - assets/newsday.png
    - assets/newzimbabwe.jpg
    - assets/southerneye.jpg
    - assets/thechronicle.png
    - assets/thefinancialgazette.jpg
    - assets/theherald1.jpg
    - assets/theherald2.jpg
    - assets/themanicapost.png
    - assets/thenewshawks.jpg
    - assets/thestandard.jpg
    - assets/thesundaymail.png
    - assets/zimeye.jpg
    - assets/zimindependent.jpg
    - assets/zimbabwemail.jpg
    - flags/botswana-flag.png
    - flags/angola-flag.png
    - flags/comoros-flag.png
    - flags/drc-flag.png
    - flags/eswatini-flag.png
    - flags/lesotho-flag.png
    - flags/madagascar-flag.png
    - flags/malawi-flag.png
    - flags/mauritius-flag.png
    - flags/mozambique-flag.png
    - flags/namibia-flag.png
    - flags/seychelles-flag.png
    - flags/southafrica-flag.png
    - flags/tanzania-flag.png
    - flags/zambia-flag.png
    - flags/zimbabwe-flag.png
    - flags/mauri-flag.png
    - angola newspaper logos/journaldeangola.png
    - angola newspaper logos/angola24horas.com.png
    - angola newspaper logos/angolaonline.png
    - angola newspaper logos/angolapress.png
    - angola newspaper logos/angonoticias.png
    - angola newspaper logos/correiodakianda.png
    - angola newspaper logos/expansao.png
    - angola newspaper logos/folha8.png
    - angola newspaper logos/makaangola.png
    - angola newspaper logos/novagazeta.png
    - angola newspaper logos/novojornal.png
    - angola newspaper logos/opais.png
    - angola newspaper logos/platinaline.png
    - angola newspaper logos/tpa.png
    - angola newspaper logos/verangola.png
    - angola newspaper logos/portaldeangola.png
    - angola newspaper logos/vozdeangola.png
    - angola newspaper logos/noticiasdeangola.png
    - angola newspaper logos/clubk.png
    - botswana newspaper logos/botswana_unplugged.png
    - botswana newspaper logos/botswanaguardian.png
    - botswana newspaper logos/dailynewsbotswana.png
    - botswana newspaper logos/mmegi.png
    - botswana newspaper logos/thebotswanagazette.png
    - botswana newspaper logos/thepatriotonsunday.png
    - botswana newspaper logos/thesundaystandard.png
    - botswana newspaper logos/thevoice.png
    - botswana newspaper logos/weekendpost.png
    - comoros newspaper logos/alwatwan.png
    - comoros newspaper logos/comoresinfos.png
    - comoros newspaper logos/habarizacomores.png
    - comoros newspaper logos/lagazettedescomores.png
    - comoros newspaper logos/lemohelien.png
    - drc newspaper logos/actualliterdc.png
    - drc newspaper logos/agp.png
    - drc newspaper logos/deskeco.png
    - drc newspaper logos/laprosperite.png
    - drc newspaper logos/radiookapi.png
    - drc newspaper logos/forumdesss.png
    - drc newspaper logos/footrdc.png
    - drc newspaper logos/congosynthese.png
    - drc newspaper logos/lephare.png
    - drc newspaper logos/voiceofcongo.png
    - drc newspaper logos/mediacongo.png
    - drc newspaper logos/congoprofond.png
    - drc newspaper logos/congoindependent.png
    - drc newspaper logos/congoplanet.png
    - drc newspaper logos/lesoft.png
    - drc newspaper logos/casinfo.png
    - eswatini newspaper logos/eswatiniobserver.png
    - eswatini newspaper logos/swazilandnews.png
    - eswatini newspaper logos/timesswaziland.png
    - lesotho newspaper logos/informative.png
    - lesotho newspaper logos/lesothotimes.png
    - lesotho newspaper logos/publiceye.png
    - lesotho newspaper logos/sundayexpress.png
    - lesotho newspaper logos/thepost.png
    - madagascar newspaper logos/lakroa.png
    - madagascar newspaper logos/laverite.png
    - madagascar newspaper logos/leexpressdemadagascar.png
    - madagascar newspaper logos/madagate.png
    - madagascar newspaper logos/midi.png
    - madagascar newspaper logos/moov.png
    - madagascar newspaper logos/newsmada.png
    - madagascar newspaper logos/nyvalosa.png
    - madagascar newspaper logos/orange.png
    - madagascar newspaper logos/tribunemadagascar.png
    - malawi newspaper logos/bizmalawi.png
    - malawi newspaper logos/businessmalawi.png
    - malawi newspaper logos/capitalfm.png
    - malawi newspaper logos/dailytimes.png
    - malawi newspaper logos/faceofomalawi.png
    - malawi newspaper logos/malawi24.png
    - malawi newspaper logos/malawifreedom.png
    - malawi newspaper logos/malawivoice.png
    - malawi newspaper logos/maraviexpress.png
    - malawi newspaper logos/nyasapost.png
    - malawi newspaper logos/nyasatimes.png
    - malawi newspaper logos/radiomaria.png
    - malawi newspaper logos/themaravipost.png
    - malawi newspaper logos/thenation.png
    - malawi newspaper logos/zodiak.png
    - mauritius newspaper logos/5plus.png
    - mauritius newspaper logos/defimedia.png
    - mauritius newspaper logos/l'express.png
    - mauritius newspaper logos/l'mauricien.png
    - mauritius newspaper logos/mauriceinfo.png
    - mauritius newspaper logos/mauritiustimes.png
    - mauritius newspaper logos/mbc.png
    - mauritius newspaper logos/sundaytimes.png
    - seychelles newspaper logos/4seasons.png
    - seychelles newspaper logos/sbc.png
    - seychelles newspaper logos/seychellesnation.png
    - seychelles newspaper logos/todayinseychelles.png
    - mozambique newspaper logos/canalmoz.png
    - mozambique newspaper logos/cartademocambique.png
    - mozambique newspaper logos/clubofmozambique.png
    - mozambique newspaper logos/desafio.png
    - mozambique newspaper logos/folha.png
    - mozambique newspaper logos/jornaltxopela.png
    - mozambique newspaper logos/mmo.png
    - mozambique newspaper logos/noticias.png
    - mozambique newspaper logos/portaldogoverno.png
    - mozambique newspaper logos/portalmoz.png
    - mozambique newspaper logos/stop.png
    - mozambique newspaper logos/tvm.png
    - mozambique newspaper logos/verdade.png
    - mozambique newspaper logos/zitamar.png
    - mozambique newspaper logos/domingo.png
    - namibia newspaper logos/99fm.png
    - namibia newspaper logos/az.png
    - namibia newspaper logos/caprivision.png
    - namibia newspaper logos/dierepublic.png
    - namibia newspaper logos/informante.png
    - namibia newspaper logos/kanaal7.png
    - namibia newspaper logos/kundana.png
    - namibia newspaper logos/nambianewsdigest.png
    - namibia newspaper logos/namibiaeconomist.png
    - namibia newspaper logos/namibiasun.png
    - namibia newspaper logos/namibtimes.png
    - namibia newspaper logos/nampa.png
    - namibia newspaper logos/nbc.png
    - namibia newspaper logos/newera.png
    - namibia newspaper logos/radiowave.png
    - namibia newspaper logos/thenamibian.png
    - namibia newspaper logos/thevillager.png
    - namibia newspaper logos/windhoekobserver.png
    - tanzania newspaper logos/bongo5.png
    - tanzania newspaper logos/businesstimes.png
    - tanzania newspaper logos/dailynews.png
    - tanzania newspaper logos/dar24.png
    - tanzania newspaper logos/globalpublishers.png
    - tanzania newspaper logos/habari.png
    - tanzania newspaper logos/ipp.png
    - tanzania newspaper logos/itv.png
    - tanzania newspaper logos/jamhuri.png
    - tanzania newspaper logos/mwanahalisa.png
    - tanzania newspaper logos/mwanaspoti.png
    - tanzania newspaper logos/startv.png
    - tanzania newspaper logos/tbc.png
    - tanzania newspaper logos/thecitizen.png
    - tanzania newspaper logos/theguardian.png
    - tanzania newspaper logos/zanzinews.png
    - zambia newspaper logos/dailynation.png
    - zambia newspaper logos/independentobserver.png
    - zambia newspaper logos/lusakastar.png
    - zambia newspaper logos/lusakatimes.png
    - zambia newspaper logos/lusakavoice.png
    - zambia newspaper logos/muvitv.png
    - zambia newspaper logos/mwebantu.png
    - zambia newspaper logos/newsdiggers.png
    - zambia newspaper logos/openzambia.png
    - zambia newspaper logos/thelowdown.png
    - zambia newspaper logos/timesofzam.png
    - zambia newspaper logos/zambiadailymail.png
    - zambia newspaper logos/zambiainvest.png
    - zambia newspaper logos/zambianeye.png
    - zambia newspaper logos/zambianobserver.png
    - zambia newspaper logos/zambianpolitics.png
    - zambia newspaper logos/zambiaonline.png
    - zambia newspaper logos/zamfoot.png
    - zambia newspaper logos/zamnews365.png
    - zambia newspaper logos/zedgossip.png
    - south africa newspaper logos/702.png
    - south africa newspaper logos/africanreporter.png
    - south africa newspaper logos/alexnews.png
    - south africa newspaper logos/algoa.png
    - south africa newspaper logos/bedfordview.png
    - south africa newspaper logos/bereamail.png
    - south africa newspaper logos/briefly.png
    - south africa newspaper logos/businessday.png
    - south africa newspaper logos/capebusinessnews.png
    - south africa newspaper logos/capetalk.png
    - south africa newspaper logos/chatsworth.png
    - south africa newspaper logos/citypress.png
    - south africa newspaper logos/dailymaverick.png
    - south africa newspaper logos/dailysun.png
    - south africa newspaper logos/dieburger.png
    - south africa newspaper logos/dieson.png
    - south africa newspaper logos/dispatchlive.png
    - south africa newspaper logos/eNCA.png
    - south africa newspaper logos/engnews.png
    - south africa newspaper logos/eyewitness.png
    - south africa newspaper logos/georgeherald.png
    - south africa newspaper logos/gremlin.png
    - south africa newspaper logos/heraldlive.png
    - south africa newspaper logos/iafrica.png
    - south africa newspaper logos/indianspice.png
    - south africa newspaper logos/isolozwe.png
    - south africa newspaper logos/itweb.png
    - south africa newspaper logos/jewsishreport.png
    - south africa newspaper logos/kempton.png
    - south africa newspaper logos/krugersdorpnews.png
    - south africa newspaper logos/letabaherald.png
    - south africa newspaper logos/lowvelder.png
    - south africa newspaper logos/mail&guardian.png
    - south africa newspaper logos/maroela.png
    - south africa newspaper logos/mayihlome.png
    - south africa newspaper logos/news24.png
    - south africa newspaper logos/ofm.png
    - south africa newspaper logos/politicsweb.png
    - south africa newspaper logos/polity.png
    - south africa newspaper logos/polokwanereview.png
    - south africa newspaper logos/potchefstroom.png
    - south africa newspaper logos/pretoriarekord.png
    - south africa newspaper logos/sabc.png
    - south africa newspaper logos/sagoodnews.png
    - south africa newspaper logos/satoday.png
    - south africa newspaper logos/sedibeng.png
    - south africa newspaper logos/sharenet.png
    - south africa newspaper logos/soccerladuma.png
    - south africa newspaper logos/southcoastherald.png
    - south africa newspaper logos/southcoastsun.png
    - south africa newspaper logos/sowetan.png
    - south africa newspaper logos/techcentral.png
    - south africa newspaper logos/thecitizen.png
    - south africa newspaper logos/thedailyvoice.png
    - south africa newspaper logos/thesouthafrican.png
    - south africa newspaper logos/timelive.png
    - south africa newspaper logos/vaalweekblad.png
    - south africa newspaper logos/zululandobserver.png
    - south africa newspaper logos/alberton.png
    - south africa newspaper logos/grocottsmail.png
    - zim newspaper logos/bmetro.png
    - zim newspaper logos/dailynews.png
    - zim newspaper logos/herald.png
    - zim newspaper logos/hmetreo.png
    - zim newspaper logos/kwayedza.png
    - zim newspaper logos/masvingomirror.png
    - zim newspaper logos/newsday.png
    - zim newspaper logos/newzimbabwe.png
    - zim newspaper logos/thechronicle.png
    - zim newspaper logos/thefinancialgazette.png
    - zim newspaper logos/thesundaymail.png
    - zim newspaper logos/thesundaymail2.png
    - zim newspaper logos/thezimbabwedaily.png
    - zim newspaper logos/thezimbabwemail.png
    - zim newspaper logos/zimeye.png
    - zim newspaper logos/zimindependent.png
    - zim newspaper logos/zimlive.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
